source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-soopr-seo-tag", "~> 2.7.3"
gem "jekyll-markdown-output", "~> 0.1"
gem "jekyll-llms-output", "~> 0.1"